version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    env_file:
      - .env.client
    depends_on:
      - backend
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
  db:
    image: postgres:13-alpine
    env_file:
      - .env.db